import type {Metadata} from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Amphora Spa',
  description: 'Generated by',
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en-US">
    <head>
      <title>Edem</title>
      
      <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8"/>
      
      <link rel="profile" href="http://gmpg.org/xfn/11"/>
      <link rel="pingback" href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/xmlrpc.php"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="dns-prefetch" href="https://fonts.googleapis.com/"/>
      <link rel="dns-prefetch" href="https://s.w.org/"/>
      <link rel="alternate" type="application/rss+xml" title="Edem » Feed"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/feed/"/>
      <link rel="alternate" type="application/rss+xml" title="Edem » Comments Feed"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/comments/feed/"/>
      
      <link rel="https://api.w.org/" href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-json/"/>
      
      <link rel="alternate" type="application/json"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-json/wp/v2/pages/8"/>
      
      <link rel="EditURI" type="application/rsd+xml" title="RSD"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/xmlrpc.php?rsd"/>
      
      <link rel="wlwmanifest" type="application/wlwmanifest+xml"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-includes/wlwmanifest.xml"/>
      
      <meta name="generator" content="WordPress 5.5.3"/>
      
      <link rel="canonical" href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/"/>
      
      <link rel="shortlink" href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/"/>
      
      <link rel="alternate" type="application/json+oembed"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fld-wp73.template-help.com%2Fwordpress%2Fprod_14770%2Fv1%2F"/>
      
      
      <link rel="alternate" type="text/xml+oembed"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fld-wp73.template-help.com%2Fwordpress%2Fprod_14770%2Fv1%2F&amp;format=xml"/>
      
      
      <link rel="icon"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-content/uploads/2020/11/cropped-retina-logo-1-32x32.png"
            sizes="32x32"/>
      
      
      <link rel="icon"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-content/uploads/2020/11/cropped-retina-logo-1-192x192.png"
            sizes="192x192"/>
      
      
      <link rel="apple-touch-icon"
            href="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-content/uploads/2020/11/cropped-retina-logo-1-180x180.png"/>
      
      
      <meta name="msapplication-TileImage"
            content="https://ld-wp73.template-help.com/wordpress/prod_14770/v1/wp-content/uploads/2020/11/cropped-retina-logo-1-270x270.png"/>
      <script src="./Edem0_files/wp-emoji-release.min.js" type="text/javascript"></script>
      <script type="text/javascript" src="./Edem0_files/jquery.js" id="jquery-core-js"></script>
      <script type="text/javascript" src="./Edem0_files/js(1)"></script>
      <script type="text/javascript" src="./Edem0_files/analytics.js"></script>
      <script src="./Edem0_files/gtm.js"></script>
      <script src="./Edem0_files/3ts2ksMwXvKRuG480KNifJ2_JNM.js"></script>
      <script src="./Edem0_files/4o300efCt-CXoq1JEC-sVReFz48.js"></script>
      
      
      <link rel="stylesheet" id="wp-block-library-css" href="./Edem0_files/style.min.css" type="text/css" media="all"/>
      <link rel="stylesheet" id="contact-form-7-css" href="./Edem0_files/styles.css" type="text/css" media="all"/>
      <link rel="stylesheet" id="font-awesome-css" href="./Edem0_files/font-awesome.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="kava-parent-theme-style-css" href="./Edem0_files/style.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="kava-theme-style-css" href="./Edem0_files/style(1).css" type="text/css" media="all"/>
      <link rel="stylesheet" id="kava-theme-main-style-css" href="./Edem0_files/theme.css" type="text/css" media="all"/>
      <link rel="stylesheet" id="blog-layouts-module-css" href="./Edem0_files/blog-layouts-module.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="cx-google-fonts-kava-css" href="./Edem0_files/css" type="text/css" media="all"/>
      <link rel="stylesheet" id="font-awesome-all-css" href="./Edem0_files/all.min.css" type="text/css" media="all"/>
      <link rel="stylesheet" id="font-awesome-v4-shims-css" href="./Edem0_files/v4-shims.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="jet-menu-public-css" href="./Edem0_files/public.css" type="text/css" media="all"/>
      <link rel="stylesheet" id="jet-blocks-css" href="./Edem0_files/jet-blocks.css" type="text/css" media="all"/>
      <link rel="stylesheet" id="jet-elements-css" href="./Edem0_files/jet-elements.css" type="text/css" media="all"/>
      <link rel="stylesheet" id="jet-elements-skin-css" href="./Edem0_files/jet-elements-skin.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="elementor-icons-css" href="./Edem0_files/elementor-icons.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="elementor-animations-css" href="./Edem0_files/animations.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="elementor-frontend-legacy-css" href="./Edem0_files/frontend-legacy.min.css"
            type="text/css" media="all"/>
      <link rel="stylesheet" id="elementor-frontend-css" href="./Edem0_files/frontend.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="jet-tricks-frontend-css" href="./Edem0_files/jet-tricks-frontend.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="kava-extra-nucleo-outline-css" href="./Edem0_files/nucleo-outline.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="google-fonts-1-css" href="./Edem0_files/css(1)" type="text/css" media="all"/>
      <link rel="stylesheet" id="elementor-icons-shared-0-css" href="./Edem0_files/fontawesome.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="elementor-icons-fa-brands-css" href="./Edem0_files/brands.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="elementor-icons-fa-solid-css" href="./Edem0_files/solid.min.css" type="text/css"
            media="all"/>
      <link rel="stylesheet" id="elementor-icons-fa-regular-css" href="./Edem0_files/regular.min.css" type="text/css"
            media="all"/>
    
    
    </head>
    
    
    <body className="home page-template
    page-template-elementor_header_footer
    page page-id-8 wp-custom-logo layout-fullwidth
     blog-default jet-desktop-menu-active elementor-default elementor-template-full-width
     elementor-kit-1 elementor-page elementor-page-8" data-elementor-device-mode="desktop"
          data-new-gr-c-s-check-loaded="14.1146.0" data-gr-ext-installed="">
    
    
    {children}
    
    
    </body>
    </html>
  );
}
